package co.edu.udea.mantpriorivias;

import co.edu.udea.mantpriorivias.archivos.ArchivoExcel;
import co.edu.udea.mantpriorivias.constantes.Constantes;
import co.edu.udea.mantpriorivias.entidades.Alternativa;
import co.edu.udea.mantpriorivias.entidades.InfoVia;
import co.edu.udea.mantpriorivias.entidades.Item;
import co.edu.udea.mantpriorivias.entidades.MantPriorViasInfo;
import co.edu.udea.mantpriorivias.entidades.Presupuesto;
import co.edu.udea.mantpriorivias.entidades.Resumen;
import co.edu.udea.mantpriorivias.general.Util;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;

public class MantenimientoJDialog extends javax.swing.JDialog {

    private final MantPriorViasInfo mantPriorViasInfo;
    private ArchivoExcel archivoExcel = new ArchivoExcel();
    private List<String> listaDaniosComboBox = new ArrayList<>();
    private List<Alternativa> alternativasMantenimiento = new ArrayList<>();
    private List<Resumen> viasResumen = new ArrayList<>();
    private String resumen = null;
    private String via;
    private String unidad;
    private int posicionDanio;
    private double presupuestoActual;
    private double presupuestoAdicional = 0.0;
    private double valorUnitario;
    private Item itemSeleccionado;
    private Item itemVacio = new Item("Seleccione", "");
    private static final ImageIcon ERROR_IMAGE = new ImageIcon(Aplicacion.class
            .getResource("/co/edu/udea/mantpriorivias/recursos/imagenes/"
                    + "ic_dialog_error.png"));
    private static final ImageIcon WARNING_IMAGE = new ImageIcon(Aplicacion.class
            .getResource("/co/edu/udea/mantpriorivias/recursos/imagenes/"
                    + "ic_dialog_warning.png"));
    private static final ImageIcon INFORMATION_IMAGE = new ImageIcon(Aplicacion.class
            .getResource("/co/edu/udea/mantpriorivias/recursos/imagenes/"
                    + "info_48.png"));
    private final ListCellRenderer mantenimientosComboRenderer = new DefaultListCellRenderer() {
        @Override
        public Component getListCellRendererComponent(JList<?> list,
                Object value, int index, boolean isSelected,
                boolean cellHasFocus) {
            if (value instanceof Item) {
                setToolTipText(((Item) value).getItem());
                value = ((Item) value).getCodigo();
            } else {
                setToolTipText("");
                value = "";
            }
            return super.getListCellRendererComponent(list, value, index,
                    isSelected, cellHasFocus);
        }
    };

    /**
     * Creates new form CostosMantenimientoJDialog
     *
     * @param parent
     * @param modal
     * @param mantPriorViasInfo
     */
    public MantenimientoJDialog(java.awt.Frame parent, boolean modal,
            MantPriorViasInfo mantPriorViasInfo) {
        super(parent, modal);
        this.mantPriorViasInfo = mantPriorViasInfo;
        initComponents();

        this.setInformacionPresupuesto(this.mantPriorViasInfo.getPresupuesto());
        this.setCodigosVias(this.mantPriorViasInfo.getVias());

        this.setLocationRelativeTo(parent);
        this.setResizable(false);

        this.setTitle("Mantenimiento y Mejoramiento de Vías");

        this.restringirValoresCampos();
        this.aplicarMantenimientoButton.setEnabled(false);
        this.presupuestoActualTextField.setBackground(Color.green);
        this.presupuestoAdicionalTextField.setText(
                String.valueOf(this.presupuestoAdicional));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        presupuestoTotlaInicialLabel = new javax.swing.JLabel();
        presupuestoTotalInicialTextField = new javax.swing.JTextField();
        porcentajeAdministracionLabel = new javax.swing.JLabel();
        porcentajeAdministracionTextField = new javax.swing.JTextField();
        porcentajeImprevistosLabel = new javax.swing.JLabel();
        porcentajeUtilidadesTextField = new javax.swing.JTextField();
        porcentajeUtilidadesLabel = new javax.swing.JLabel();
        presupuestoDisponibleLabel = new javax.swing.JLabel();
        presupuestoDisponibleTextField = new javax.swing.JTextField();
        codigosViasComboBox = new javax.swing.JComboBox();
        viasLabel = new javax.swing.JLabel();
        presupuestoActualTextField = new javax.swing.JTextField();
        presupuestoActualLabel = new javax.swing.JLabel();
        presupuestoAdicionalLabel = new javax.swing.JLabel();
        presupuestoAdicionalTextField = new javax.swing.JTextField();
        porcentajeImprevistosTextField = new javax.swing.JTextField();
        daniosAsociadosLabel = new javax.swing.JLabel();
        daniosComboBox = new javax.swing.JComboBox();
        costoUnitarioMantenimientoLabel = new javax.swing.JLabel();
        precioMantenimientoMejoraTextField = new javax.swing.JTextField();
        unidadMedidaMantenimientoLabel = new javax.swing.JLabel();
        unidadMedidaMantenimientoTextField = new javax.swing.JTextField();
        cantidadMantenimientoMejoraTextField = new javax.swing.JTextField();
        cantidadLabel = new javax.swing.JLabel();
        mantenimientosRecomendadosLabel = new javax.swing.JLabel();
        mantenimientosComboBox = new javax.swing.JComboBox();
        aplicarMantenimientoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumenTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        abrirAlternativasIntervencionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelTitulo.setText("Priorización y Mantenimiento de Vías");

        presupuestoTotlaInicialLabel.setText("Presupuesto Total Inicial");

        presupuestoTotalInicialTextField.setEditable(false);
        presupuestoTotalInicialTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        porcentajeAdministracionLabel.setText("% Administración");

        porcentajeAdministracionTextField.setEditable(false);
        porcentajeAdministracionTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        porcentajeImprevistosLabel.setText("% Imprevistos");

        porcentajeUtilidadesTextField.setEditable(false);
        porcentajeUtilidadesTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        porcentajeUtilidadesLabel.setText("% Utilidades");

        presupuestoDisponibleLabel.setText("Presupuesto Disponible");

        presupuestoDisponibleTextField.setEditable(false);
        presupuestoDisponibleTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        codigosViasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigosViasComboBoxActionPerformed(evt);
            }
        });

        viasLabel.setText("Vías");

        presupuestoActualTextField.setEditable(false);
        presupuestoActualTextField.setForeground(java.awt.Color.black);
        presupuestoActualTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        presupuestoActualLabel.setText("Presupuesto actual");

        presupuestoAdicionalLabel.setText("Presupuesto adicional");

        presupuestoAdicionalTextField.setEditable(false);
        presupuestoAdicionalTextField.setForeground(java.awt.Color.black);
        presupuestoAdicionalTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        porcentajeImprevistosTextField.setEditable(false);
        porcentajeImprevistosTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        daniosAsociadosLabel.setText("Daños asociados a la vía");

        daniosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daniosComboBoxActionPerformed(evt);
            }
        });

        costoUnitarioMantenimientoLabel.setText("Costo unitario del mantenimiento");

        precioMantenimientoMejoraTextField.setEditable(false);

        unidadMedidaMantenimientoLabel.setText("Unidad de medida del matenimiento");

        unidadMedidaMantenimientoTextField.setEditable(false);
        unidadMedidaMantenimientoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unidadMedidaMantenimientoTextFieldActionPerformed(evt);
            }
        });

        cantidadMantenimientoMejoraTextField.setEditable(false);
        cantidadMantenimientoMejoraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadMantenimientoMejoraTextFieldActionPerformed(evt);
            }
        });

        cantidadLabel.setText("Cantidad");

        mantenimientosRecomendadosLabel.setText("Mantenimientos recomendados");

        mantenimientosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientosComboBoxActionPerformed(evt);
            }
        });

        aplicarMantenimientoButton.setText("Aplicar Mantenimiento");
        aplicarMantenimientoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarMantenimientoButtonActionPerformed(evt);
            }
        });

        resumenTextArea.setColumns(20);
        resumenTextArea.setRows(5);
        jScrollPane1.setViewportView(resumenTextArea);

        archivoMenu.setText("Archivo");

        abrirAlternativasIntervencionMenuItem.setText("Abrir alternativas intervención");
        abrirAlternativasIntervencionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirAlternativasIntervencionMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(abrirAlternativasIntervencionMenuItem);

        jMenuBar1.add(archivoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigosViasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viasLabel))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(daniosAsociadosLabel)
                                    .addComponent(daniosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mantenimientosRecomendadosLabel)
                                    .addComponent(mantenimientosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(389, 389, 389))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(precioMantenimientoMejoraTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costoUnitarioMantenimientoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(unidadMedidaMantenimientoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(unidadMedidaMantenimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantidadMantenimientoMejoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aplicarMantenimientoButton)
                        .addGap(555, 555, 555))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presupuestoTotlaInicialLabel)
                            .addComponent(presupuestoTotalInicialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcentajeAdministracionLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(porcentajeAdministracionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcentajeImprevistosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(porcentajeImprevistosLabel))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(porcentajeUtilidadesLabel)
                            .addComponent(porcentajeUtilidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presupuestoDisponibleLabel)
                            .addComponent(presupuestoDisponibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(presupuestoActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(presupuestoActualLabel)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(presupuestoAdicionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(presupuestoAdicionalLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presupuestoDisponibleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presupuestoDisponibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(presupuestoTotlaInicialLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(presupuestoTotalInicialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(porcentajeAdministracionLabel)
                                .addComponent(porcentajeImprevistosLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(porcentajeAdministracionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(porcentajeImprevistosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(porcentajeUtilidadesLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(porcentajeUtilidadesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presupuestoActualLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presupuestoActualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(presupuestoAdicionalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(presupuestoAdicionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(daniosAsociadosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(daniosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mantenimientosRecomendadosLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mantenimientosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoUnitarioMantenimientoLabel)
                            .addComponent(unidadMedidaMantenimientoLabel)
                            .addComponent(cantidadLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigosViasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioMantenimientoMejoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadMedidaMantenimientoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadMantenimientoMejoraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aplicarMantenimientoButton)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirAlternativasIntervencionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirAlternativasIntervencionMenuItemActionPerformed
        String ruta = Util.getRutaTemporal();
        try {
            boolean resultado;
            resultado = this.archivoExcel.
                    descargarAlternativasIntervencion(new File(ruta));
            if (!resultado) {
                JOptionPane.showMessageDialog(this, "No se puede abrir el archivo"
                        + " de alternativas de intervención.\n\nPor favor "
                        + "conctátese con el administrador de la aplicación.",
                        "Error en archivo", JOptionPane.ERROR_MESSAGE, ERROR_IMAGE);
            } else {
                if (Desktop.isDesktopSupported()) {
                    Desktop desktop = Desktop.getDesktop();
                    desktop.open(new File(ruta + "/"
                            + ArchivoExcel.ARCHIVO_ALTERNATIVAS_INTERVENCION));
                } else {
                    JOptionPane.showMessageDialog(this,
                            "No se puede abrir el archivo"
                            + " de alternativas de intervención.\n\nPor favor "
                            + "contáctese con el administrador de la aplicación.",
                            "No se puede abrir archivos",
                            JOptionPane.WARNING_MESSAGE, WARNING_IMAGE);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(MantenimientoJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_abrirAlternativasIntervencionMenuItemActionPerformed

    private void codigosViasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigosViasComboBoxActionPerformed
        this.via = (String) this.codigosViasComboBox.getSelectedItem();
        this.mantenimientosComboBox.removeAllItems();
        this.mantenimientosComboBox.addItem(this.itemVacio);
        this.mantenimientosComboBox.setRenderer(this.mantenimientosComboRenderer);
        System.out.println(this.via);

        List<String> danios = this.obtenerDaniosDadoUnaVia(this.via);
        if (danios.contains("89N")) {
            danios.remove("89N");
        }

        this.daniosComboBox.removeAllItems();
        this.listaDaniosComboBox.clear();

        this.daniosComboBox.addItem("Seleccione");
        this.listaDaniosComboBox.add("Seleccione");
        danios.stream().forEach(s -> {
            this.daniosComboBox.addItem(Constantes.NOMBRES_DANIOS.get(
                    s.substring(0, s.length() - 1)) + " - " + s.substring(2));
            this.listaDaniosComboBox.add(s);
        });
    }//GEN-LAST:event_codigosViasComboBoxActionPerformed

    private void daniosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daniosComboBoxActionPerformed
        this.posicionDanio = this.daniosComboBox.getSelectedIndex();
        if (this.listaDaniosComboBox != null && !this.listaDaniosComboBox.isEmpty()
                && this.posicionDanio >= 0) {
            String danioSeleccionado = this.listaDaniosComboBox.get(this.posicionDanio);
            String alternativasIntervencion = Constantes.ALTERNATIVAS_INTERVENCION_MANTENIMIENTO.get(
                    danioSeleccionado);
            if (alternativasIntervencion != null) {
                List<String> mantenimientosMejoras = Util.tokenizar(
                        alternativasIntervencion, ",");
                List<Item> itemsObject = new ArrayList<>();
                this.mantPriorViasInfo.getItems().stream().forEach(i -> {
                    mantenimientosMejoras.stream().forEach(m -> {
                        if (m.equals(i.getCodigo())) {
                            itemsObject.add(i);
                        }
                    });
                });

                this.mantenimientosComboBox.removeAllItems();
                this.mantenimientosComboBox.addItem(this.itemVacio);
                itemsObject.stream().forEach(i -> {
                    this.mantenimientosComboBox.addItem(i);
                });
                this.mantenimientosComboBox.setRenderer(this.mantenimientosComboRenderer);
            } else {
                this.mantenimientosComboBox.removeAllItems();
                this.mantenimientosComboBox.addItem(this.itemVacio);
            }
        }
    }//GEN-LAST:event_daniosComboBoxActionPerformed

    private void cantidadMantenimientoMejoraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadMantenimientoMejoraTextFieldActionPerformed
    }//GEN-LAST:event_cantidadMantenimientoMejoraTextFieldActionPerformed

    private void mantenimientosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientosComboBoxActionPerformed
        int posicionItemSeleccionado = this.mantenimientosComboBox.getSelectedIndex();
        if (posicionItemSeleccionado <= 0) {
            this.cantidadMantenimientoMejoraTextField.setEditable(false);
            this.cantidadMantenimientoMejoraTextField.setText("");
            this.precioMantenimientoMejoraTextField.setText("");
            this.unidadMedidaMantenimientoTextField.setText("");
            this.aplicarMantenimientoButton.setEnabled(false);
        } else {
            this.aplicarMantenimientoButton.setEnabled(true);
            this.cantidadMantenimientoMejoraTextField.setEditable(true);
            this.itemSeleccionado = (Item) this.mantenimientosComboBox.
                    getSelectedItem();
            this.valorUnitario = this.buscarPrecioDadoCodigoItem(
                    this.itemSeleccionado.getCodigo());
            this.unidad = this.buscarUnidadDadoCodigoItem(
                    this.itemSeleccionado.getCodigo());
            this.precioMantenimientoMejoraTextField.setText("$ "
                    + String.valueOf(this.valorUnitario));
            this.unidadMedidaMantenimientoTextField.setText(this.unidad);

            Alternativa mantenimiento = this.buscarMantenimientoAplicadoDadoViaItemMantenimiento(
                    this.via, this.listaDaniosComboBox.get(this.posicionDanio),
                    this.itemSeleccionado.getCodigo());

            if (mantenimiento != null) {
                this.cantidadMantenimientoMejoraTextField.setText(
                        String.valueOf(mantenimiento.getCantidad()).replace(".0", ""));
            } else {
                this.cantidadMantenimientoMejoraTextField.setText("");
            }
        }
    }//GEN-LAST:event_mantenimientosComboBoxActionPerformed

    private void aplicarMantenimientoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarMantenimientoButtonActionPerformed
        Alternativa mantenimiento = this.buscarMantenimientoAplicadoDadoViaItemMantenimiento(
                this.via, this.listaDaniosComboBox.get(this.posicionDanio),
                this.itemSeleccionado.getCodigo());

        if (this.cantidadMantenimientoMejoraTextField.getText() == null
                || this.cantidadMantenimientoMejoraTextField.getText().trim().isEmpty()) {
            if (mantenimiento == null) {
                JOptionPane.showMessageDialog(this,
                        "No se ha agregado el mantenimiento porque no se ha ingresado"
                        + " la cantidad", "No se aplicó mantenimiento.",
                        JOptionPane.WARNING_MESSAGE, WARNING_IMAGE);

                return;
            } else {
                this.alternativasMantenimiento.remove(mantenimiento);
                if (this.presupuestoActual == 0.0) {
                    double t = mantenimiento.getCantidad()
                            * this.buscarPrecioDadoCodigoItem(mantenimiento.getItem());
                    if (t < this.presupuestoAdicional) {
                        this.presupuestoAdicional = this.presupuestoAdicional - t;
                    } else if (t == this.presupuestoAdicional) {
                        this.presupuestoAdicional = 0.0;
                    } else {
                        double p = t - this.presupuestoAdicional;
                        this.presupuestoAdicional = 0;
                        this.presupuestoActual += p;
                    }
                } else {
                    this.presupuestoActual = this.presupuestoActual + (mantenimiento.getCantidad()
                            * this.buscarPrecioDadoCodigoItem(mantenimiento.getItem()));
                }

                this.establecerPresupuesto();
                JOptionPane.showMessageDialog(this,
                        "Se ha eliminado el mantenimiento aplicado correctamente",
                        "Mantenimiento aplicado eliminado",
                        JOptionPane.INFORMATION_MESSAGE, INFORMATION_IMAGE);

                this.crearResumenMantenimientoMejoras();
                this.eliminarAlternativaResumen(mantenimiento);

                return;
            }
        }

        if (!Util.isNumerico(this.cantidadMantenimientoMejoraTextField.getText())) {
            JOptionPane.showMessageDialog(this,
                    "El valor ingresado no es un número válido", "Valor no numérico",
                    JOptionPane.WARNING_MESSAGE, WARNING_IMAGE);

            return;
        }

        if (Util.isNumerico(this.cantidadMantenimientoMejoraTextField.getText())
                && Double.parseDouble(this.cantidadMantenimientoMejoraTextField.getText()) <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El valor ingresado debe ser mayor que cero", "Valor no válido",
                    JOptionPane.WARNING_MESSAGE, WARNING_IMAGE);

            return;
        }

        double cantidad = Double.parseDouble(
                this.cantidadMantenimientoMejoraTextField.getText().trim());
        if (mantenimiento != null) {
            if (mantenimiento.getCantidad() == cantidad) {
                JOptionPane.showMessageDialog(this,
                        "No se ha aplicado el mantenimiento porque ya existe uno con "
                        + "los mismos valores", "Mantenimiento no aplicado",
                        JOptionPane.WARNING_MESSAGE, WARNING_IMAGE);

                return;
            } else {
                this.alternativasMantenimiento.remove(mantenimiento);
                double cantidadTemp = cantidad;
                cantidad = cantidadTemp - mantenimiento.getCantidad();
                mantenimiento.setCantidad(cantidadTemp);
                double precioMantenimiento = Math.abs(cantidad * this.valorUnitario);
                if (cantidad < 0) {
                    if (this.presupuestoAdicional > 0) {
                        double t = this.presupuestoAdicional - precioMantenimiento;
                        if (t > 0) {
                            this.presupuestoAdicional = t;
                        } else if (t == 0) {
                            this.presupuestoAdicional = 0;
                        } else {
                            this.presupuestoAdicional = 0;
                            this.presupuestoActual += Math.abs(t);
                        }
                    } else {
                        this.presupuestoActual += precioMantenimiento;
                    }
                } else {
                    if (this.presupuestoAdicional > 0) {
                        this.presupuestoAdicional += precioMantenimiento;
                    } else {
                        double t = this.presupuestoActual - precioMantenimiento;
                        if (t > 0) {
                            this.presupuestoActual = t;
                        } else if (t == 0) {
                            this.presupuestoActual = 0;
                        } else {
                            this.presupuestoActual = 0;
                            this.presupuestoAdicional = Math.abs(t);
                        }
                    }
                }
                this.alternativasMantenimiento.add(mantenimiento);

                this.establecerPresupuesto();
                this.crearResumenMantenimientoMejoras();
                this.agregarAlternativaResumen(mantenimiento);

                return;
            }
        }

        if (this.presupuestoAdicional > 0) {
            this.presupuestoAdicional += cantidad * this.valorUnitario;
        } else {
            double t = this.presupuestoActual - cantidad * this.valorUnitario;
            if (t >= 0) {
                this.presupuestoActual = t;
            } else {
                this.presupuestoActual = 0;
                this.presupuestoAdicional = Math.abs(t);
            }
        }

        this.establecerPresupuesto();

        Alternativa alternativa = new Alternativa();
        alternativa.setCodigoVia(this.via);
        alternativa.setItem(this.itemSeleccionado.getCodigo());
        alternativa.setDanio(this.listaDaniosComboBox.get(this.posicionDanio));
        alternativa.setCantidad(cantidad);
        this.alternativasMantenimiento.add(alternativa);

        this.agregarAlternativaResumen(alternativa);
    }//GEN-LAST:event_aplicarMantenimientoButtonActionPerformed

    private void unidadMedidaMantenimientoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unidadMedidaMantenimientoTextFieldActionPerformed
    }//GEN-LAST:event_unidadMedidaMantenimientoTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirAlternativasIntervencionMenuItem;
    private javax.swing.JButton aplicarMantenimientoButton;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTextField cantidadMantenimientoMejoraTextField;
    private javax.swing.JComboBox codigosViasComboBox;
    private javax.swing.JLabel costoUnitarioMantenimientoLabel;
    private javax.swing.JLabel daniosAsociadosLabel;
    private javax.swing.JComboBox daniosComboBox;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JComboBox mantenimientosComboBox;
    private javax.swing.JLabel mantenimientosRecomendadosLabel;
    private javax.swing.JLabel porcentajeAdministracionLabel;
    private javax.swing.JTextField porcentajeAdministracionTextField;
    private javax.swing.JLabel porcentajeImprevistosLabel;
    private javax.swing.JTextField porcentajeImprevistosTextField;
    private javax.swing.JLabel porcentajeUtilidadesLabel;
    private javax.swing.JTextField porcentajeUtilidadesTextField;
    private javax.swing.JTextField precioMantenimientoMejoraTextField;
    private javax.swing.JLabel presupuestoActualLabel;
    private javax.swing.JTextField presupuestoActualTextField;
    private javax.swing.JLabel presupuestoAdicionalLabel;
    private javax.swing.JTextField presupuestoAdicionalTextField;
    private javax.swing.JLabel presupuestoDisponibleLabel;
    private javax.swing.JTextField presupuestoDisponibleTextField;
    private javax.swing.JTextField presupuestoTotalInicialTextField;
    private javax.swing.JLabel presupuestoTotlaInicialLabel;
    private javax.swing.JTextArea resumenTextArea;
    private javax.swing.JLabel unidadMedidaMantenimientoLabel;
    private javax.swing.JTextField unidadMedidaMantenimientoTextField;
    private javax.swing.JLabel viasLabel;
    // End of variables declaration//GEN-END:variables

    public MantPriorViasInfo iniciarVentanta() {
        this.setVisible(true);

        return this.mantPriorViasInfo;
    }

    private void setInformacionPresupuesto(Presupuesto presupuesto) {
        this.presupuestoTotalInicialTextField.setText("$ "
                + presupuesto.getPresupuestoTotal());
        this.porcentajeAdministracionTextField.setText(String.valueOf(
                presupuesto.getPorcentajeAdministracion() * 100));
        this.porcentajeImprevistosTextField.setText(String.valueOf(
                presupuesto.getPorcentajeImprevistos() * 100));
        this.porcentajeUtilidadesTextField.setText(String.valueOf(
                presupuesto.getPorcentajeUtiliadades() * 100));
        this.presupuestoDisponibleTextField.setText("$ "
                + presupuesto.getPresupuestoDisponible());
        this.presupuestoActualTextField.setText("$ "
                + presupuesto.getPresupuestoDisponible());

        this.presupuestoActual = presupuesto.getPresupuestoDisponible();
    }

    private void setCodigosVias(List<InfoVia> vias) {
        this.codigosViasComboBox.addItem("Seleccione");
        vias.stream().forEach((v) -> {
            this.codigosViasComboBox.addItem(v.getVia().getCodigoVia().trim());
        });
    }

    private List<String> obtenerDaniosDadoUnaVia(String via) {
        List<String> danios = new ArrayList<>();

        for (InfoVia iv : mantPriorViasInfo.getVias()) {
            if (iv.getVia().getCodigoVia().equals(via)) {
                danios = iv.getDaniosSeleccionados();

                break;
            }
        }

        return danios;
    }

    private void restringirValoresCampos() {
        this.cantidadMantenimientoMejoraTextField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE) || c == KeyEvent.VK_PERIOD)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    private double buscarPrecioDadoCodigoItem(String codigoItem) {
        double precio = 0.0;
        for (Item i : this.mantPriorViasInfo.getItems()) {
            if (i.getCodigo().equals(codigoItem)) {
                precio = i.getValorUnitario();
            }
        }

        return precio;
    }

    private String buscarUnidadDadoCodigoItem(String codigoItem) {
        String u = "";
        for (Item i : this.mantPriorViasInfo.getItems()) {
            if (i.getCodigo().equals(codigoItem)) {
                u = i.getUnidad();
            }
        }

        return u;
    }

    private Alternativa buscarMantenimientoAplicadoDadoViaItemMantenimiento(String via,
            String danio, String item) {
        Alternativa alternativa = null;
        for (Alternativa a : this.alternativasMantenimiento) {
            if (via.equals(a.getCodigoVia()) && danio.equals(a.getDanio())
                    && item.equals(a.getItem())) {
                return a;
            }
        }

        return alternativa;
    }

    private void establecerColorPresupuestoActual() {
        double porcentaje = this.presupuestoActual
                / this.mantPriorViasInfo.getPresupuesto().getPresupuestoDisponible();
        if (porcentaje > 0.6) {
            // Verde
            this.presupuestoActualTextField.setBackground(Color.green);
        } else if (porcentaje > 0.2 && porcentaje <= 0.6) {
            // Naranja
            this.presupuestoActualTextField.setBackground(Color.orange);
        } else {
            // Rojo
            this.presupuestoActualTextField.setBackground(Color.red);
        }
    }

    private void establecerPresupuesto() {
        this.establecerColorPresupuestoActual();
        this.presupuestoActualTextField.setText("$ " + this.presupuestoActual);
        this.presupuestoAdicionalTextField.setText("$ " + this.presupuestoAdicional);
    }

    private void crearResumenMantenimientoMejoras() {
        String separadorLinea = System.getProperty("line.separator");
        String resumen = "MANTENIMIENTO APLICADO:" + separadorLinea + separadorLinea;

    }

    private void agregarAlternativaResumen(Alternativa alternativa) {
        int posicion = this.contieneVia(alternativa.getCodigoVia());
        if (posicion < 0) {
            Resumen r = new Resumen();
            r.setVia(alternativa.getCodigoVia());
            r.getDaniosPorVia().add(alternativa.getDanio());
            List<Alternativa> a = new ArrayList<>();
            a.add(alternativa);
            r.getAlternativasPorDanio().add(a);
            this.viasResumen.add(r);
        } else {
            Resumen r = this.viasResumen.get(posicion);
            if (!r.getDaniosPorVia().contains(alternativa.getDanio())) {
                r.getDaniosPorVia().add(alternativa.getDanio());
                List<Alternativa> a = new ArrayList<>();
                a.add(alternativa);
                r.getAlternativasPorDanio().add(a);
            } else {
                int pd = r.getDaniosPorVia().indexOf(alternativa.getDanio());
                List<Alternativa> alts = r.getAlternativasPorDanio().get(pd);
                int posicionAlternativa = this.contieneAlternativa(alts, alternativa);
                if (posicionAlternativa < 0) {
                    alts.add(alternativa);
                } else {
                    alts.set(posicionAlternativa, alternativa);
                }
            }
        }
        
        this.mostrarResumen();
    }

    private void eliminarAlternativaResumen(Alternativa alternativa) {
        int posVia = this.contieneVia(alternativa.getCodigoVia());
        Resumen r = this.viasResumen.get(posVia);
        int pd = r.getDaniosPorVia().indexOf(alternativa.getDanio());
        int pa = r.getAlternativasPorDanio().get(pd).indexOf(alternativa);
        if (r.getAlternativasPorDanio().get(pd).size() == 1) {
            r.getAlternativasPorDanio().remove(pa);
            r.getDaniosPorVia().remove(pd);
            if (0 == r.getDaniosPorVia().size()) {
                this.viasResumen.remove(posVia);
            }
        } else {
            r.getAlternativasPorDanio().get(pd).remove(pa);
        }
        
        this.mostrarResumen();
    }

    private int contieneAlternativa(List<Alternativa> alternativas, Alternativa alternativa) {
        for (int i = 0; i < alternativas.size(); i++) {
            Alternativa a = alternativas.get(i);
            if (a.getCodigoVia().equals(alternativa.getCodigoVia())
                    && a.getDanio().equals(alternativa.getDanio())
                    && a.getItem().equals(alternativa.getItem())) {
                return i;
            }
        }

        return -1;
    }

    private int contieneVia(String via) {
        for (int i = 0; i < this.viasResumen.size(); i++) {
            if (this.viasResumen.get(i).getVia().equals(via)) {

                return i;
            }
        }

        return -1;
    }

    private void mostrarResumen() {        
        String separadorLinea = System.getProperty("line.separator");
        this.resumen = "RESUMEN" + separadorLinea + "-----------------------" 
                + separadorLinea + separadorLinea;
        for(Resumen r : this.viasResumen){
            this.resumen += r.getVia();
            this.resumen += separadorLinea;
            for(int i = 0; i < r.getDaniosPorVia().size(); i++){
                this.resumen += r.getDaniosPorVia().get(i);
                this.resumen += separadorLinea;
                List<List<Alternativa>> alternativasPorDanio = r.getAlternativasPorDanio();
                
            }
        }
    }
}
