package co.edu.udea.mantpriorivias.gui;

public class AcercadeJDialog extends javax.swing.JDialog {

    /**
     * Creates new form AcercadeJDialog
     *
     * @param parent
     * @param modal
     */
    public AcercadeJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelNombreAutor = new javax.swing.JLabel();
        labelCiudadUniversidad = new javax.swing.JLabel();
        labelAnio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelTitulo.setText("Mantenimiento y Priorización de Vías");

        labelNombreAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNombreAutor.setText("Juliet Andrea Vásquez Mesa");

        labelCiudadUniversidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCiudadUniversidad.setText("Medellin - Universidad de Antioquia");

        labelAnio.setText("2015");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(labelNombreAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(labelCiudadUniversidad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(labelAnio)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelTitulo)
                .addGap(60, 60, 60)
                .addComponent(labelNombreAutor)
                .addGap(18, 18, 18)
                .addComponent(labelCiudadUniversidad)
                .addGap(18, 18, 18)
                .addComponent(labelAnio)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelCiudadUniversidad;
    private javax.swing.JLabel labelNombreAutor;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
